# Generated by Django 6.0.4 on 2026-04-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('nickname', models.CharField(db_column='Nickname', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id_filmes', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=180)),
                ('ano', models.CharField(blank=True, db_column='Ano', max_length=4, null=True)),
                ('duracao', models.TimeField(blank=True, db_column='duracao', null=True)),
                ('faixa_etaria', models.IntegerField(blank=True, db_column='faixa_etaria', null=True)),
                ('sinopse', models.TextField(blank=True, db_column='Sinopse', null=True)),
                ('url_capa', models.URLField(blank=True, max_length=500, null=True)),
                ('generos', models.ManyToManyField(related_name='filmes', to='catalogo.genero')),
            ],
            options={
                'db_table': 'filmes',
            },
        ),
        migrations.CreateModel(
            name='FilmesFavoritos',
            fields=[
                ('id_filme_fav', models.AutoField(primary_key=True, serialize=False)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.filmes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.usuario')),
            ],
            options={
                'db_table': 'filmes_favoritos',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='catalogo.filmes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='catalogo.usuario')),
            ],
            options={
                'db_table': 'avaliacao',
            },
        ),
    ]
